import { createFileRoute } from "@tanstack/react-router";
import { BellRing } from "lucide-react";
import { AdminLayout } from "@/layouts/AdminLayout";
import { PageHeader } from "@/components/common/PageHeader";
import { StatusBadge } from "@/components/common/StatusBadge";
import { EmptyState, ErrorState, LoadingState } from "@/components/common/States";
import { Card, CardContent } from "@/components/ui/card";
import { useAsyncData } from "@/hooks/useAsyncData";
import { getAlerts } from "@/services/sessionService";

export const Route = createFileRoute("/admin/alerts")({
  head: () => ({
    meta: [
      { title: "Alerts — Faculty Attendance Monitor" },
      { name: "description", content: "Faculty attendance alerts raised when faculty is unavailable or no CR/LR response is received." },
      { property: "og:title", content: "Alerts — Faculty Attendance Monitor" },
      { property: "og:description", content: "Faculty attendance alerts for unavailable faculty and missed responses." },
    ],
  }),
  component: AlertsPage,
});

function AlertsPage() {
  const { data, loading, error, reload } = useAsyncData(() => getAlerts(), []);

  return (
    <AdminLayout>
      <PageHeader
        title="Notifications / Alerts"
        description="Alerts are generated by the backend when faculty is reported unavailable or no response is received within 10 minutes."
      />

      {loading ? (
        <LoadingState rows={4} />
      ) : error ? (
        <ErrorState message={error} onRetry={reload} />
      ) : (data?.length ?? 0) === 0 ? (
        <EmptyState
          title="No alerts"
          description="There are no faculty attendance alerts right now."
          icon={BellRing}
        />
      ) : (
        <div className="grid gap-4 lg:grid-cols-2">
          {(data ?? []).map((alert) => (
            <Card key={alert.id}>
              <CardContent className="space-y-3 p-4">
                <div className="grid grid-cols-[minmax(0,1fr)_auto] items-start gap-3">
                  <div className="min-w-0">
                    <p className="text-sm font-semibold">Faculty Attendance Alert</p>
                    <p className="truncate text-xs text-muted-foreground">Raised at {alert.time}</p>
                  </div>
                  <StatusBadge status={alert.status} />
                </div>
                <dl className="grid grid-cols-[auto_minmax(0,1fr)] gap-x-3 gap-y-1 text-sm">
                  <dt className="text-muted-foreground">Section</dt>
                  <dd className="truncate">{alert.section}</dd>
                  <dt className="text-muted-foreground">Subject</dt>
                  <dd className="truncate">{alert.subject}</dd>
                  <dt className="text-muted-foreground">Session</dt>
                  <dd>{alert.session}</dd>
                  <dt className="text-muted-foreground">Reported by</dt>
                  <dd>{alert.reportedBy}</dd>
                  <dt className="text-muted-foreground">Reason</dt>
                  <dd>{alert.reason}</dd>
                </dl>
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </AdminLayout>
  );
}
