/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminAlertsRouteImport } from './routes/admin.alerts'
import { Route as AdminCrLrRouteImport } from './routes/admin.cr-lr'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminSessionsRouteImport } from './routes/admin.sessions'
import { Route as AdminTimetableRouteImport } from './routes/admin.timetable'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as CrlrAnalyticsRouteImport } from './routes/crlr.analytics'
import { Route as CrlrAttendanceRouteImport } from './routes/crlr.attendance'
import { Route as CrlrDashboardRouteImport } from './routes/crlr.dashboard'
import { Route as CrlrNotificationsRouteImport } from './routes/crlr.notifications'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAlertsRoute = AdminAlertsRouteImport.update({
  id: '/admin/alerts',
  path: '/admin/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCrLrRoute = AdminCrLrRouteImport.update({
  id: '/admin/cr-lr',
  path: '/admin/cr-lr',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSessionsRoute = AdminSessionsRouteImport.update({
  id: '/admin/sessions',
  path: '/admin/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTimetableRoute = AdminTimetableRouteImport.update({
  id: '/admin/timetable',
  path: '/admin/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CrlrAnalyticsRoute = CrlrAnalyticsRouteImport.update({
  id: '/crlr/analytics',
  path: '/crlr/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CrlrAttendanceRoute = CrlrAttendanceRouteImport.update({
  id: '/crlr/attendance',
  path: '/crlr/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const CrlrDashboardRoute = CrlrDashboardRouteImport.update({
  id: '/crlr/dashboard',
  path: '/crlr/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CrlrNotificationsRoute = CrlrNotificationsRouteImport.update({
  id: '/crlr/notifications',
  path: '/crlr/notifications',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/cr-lr': typeof AdminCrLrRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/timetable': typeof AdminTimetableRoute
  '/auth/login': typeof AuthLoginRoute
  '/crlr/analytics': typeof CrlrAnalyticsRoute
  '/crlr/attendance': typeof CrlrAttendanceRoute
  '/crlr/dashboard': typeof CrlrDashboardRoute
  '/crlr/notifications': typeof CrlrNotificationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/cr-lr': typeof AdminCrLrRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/timetable': typeof AdminTimetableRoute
  '/auth/login': typeof AuthLoginRoute
  '/crlr/analytics': typeof CrlrAnalyticsRoute
  '/crlr/attendance': typeof CrlrAttendanceRoute
  '/crlr/dashboard': typeof CrlrDashboardRoute
  '/crlr/notifications': typeof CrlrNotificationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/cr-lr': typeof AdminCrLrRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/timetable': typeof AdminTimetableRoute
  '/auth/login': typeof AuthLoginRoute
  '/crlr/analytics': typeof CrlrAnalyticsRoute
  '/crlr/attendance': typeof CrlrAttendanceRoute
  '/crlr/dashboard': typeof CrlrDashboardRoute
  '/crlr/notifications': typeof CrlrNotificationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/alerts'
    | '/admin/cr-lr'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/sessions'
    | '/admin/timetable'
    | '/auth/login'
    | '/crlr/analytics'
    | '/crlr/attendance'
    | '/crlr/dashboard'
    | '/crlr/notifications'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/alerts'
    | '/admin/cr-lr'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/sessions'
    | '/admin/timetable'
    | '/auth/login'
    | '/crlr/analytics'
    | '/crlr/attendance'
    | '/crlr/dashboard'
    | '/crlr/notifications'
  id:
    | '__root__'
    | '/'
    | '/admin/alerts'
    | '/admin/cr-lr'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/sessions'
    | '/admin/timetable'
    | '/auth/login'
    | '/crlr/analytics'
    | '/crlr/attendance'
    | '/crlr/dashboard'
    | '/crlr/notifications'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAlertsRoute: typeof AdminAlertsRoute
  AdminCrLrRoute: typeof AdminCrLrRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSessionsRoute: typeof AdminSessionsRoute
  AdminTimetableRoute: typeof AdminTimetableRoute
  AuthLoginRoute: typeof AuthLoginRoute
  CrlrAnalyticsRoute: typeof CrlrAnalyticsRoute
  CrlrAttendanceRoute: typeof CrlrAttendanceRoute
  CrlrDashboardRoute: typeof CrlrDashboardRoute
  CrlrNotificationsRoute: typeof CrlrNotificationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/alerts': {
      id: '/admin/alerts'
      path: '/admin/alerts'
      fullPath: '/admin/alerts'
      preLoaderRoute: typeof AdminAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cr-lr': {
      id: '/admin/cr-lr'
      path: '/admin/cr-lr'
      fullPath: '/admin/cr-lr'
      preLoaderRoute: typeof AdminCrLrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sessions': {
      id: '/admin/sessions'
      path: '/admin/sessions'
      fullPath: '/admin/sessions'
      preLoaderRoute: typeof AdminSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/timetable': {
      id: '/admin/timetable'
      path: '/admin/timetable'
      fullPath: '/admin/timetable'
      preLoaderRoute: typeof AdminTimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crlr/analytics': {
      id: '/crlr/analytics'
      path: '/crlr/analytics'
      fullPath: '/crlr/analytics'
      preLoaderRoute: typeof CrlrAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crlr/attendance': {
      id: '/crlr/attendance'
      path: '/crlr/attendance'
      fullPath: '/crlr/attendance'
      preLoaderRoute: typeof CrlrAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crlr/dashboard': {
      id: '/crlr/dashboard'
      path: '/crlr/dashboard'
      fullPath: '/crlr/dashboard'
      preLoaderRoute: typeof CrlrDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crlr/notifications': {
      id: '/crlr/notifications'
      path: '/crlr/notifications'
      fullPath: '/crlr/notifications'
      preLoaderRoute: typeof CrlrNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAlertsRoute: AdminAlertsRoute,
  AdminCrLrRoute: AdminCrLrRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminSessionsRoute: AdminSessionsRoute,
  AdminTimetableRoute: AdminTimetableRoute,
  AuthLoginRoute: AuthLoginRoute,
  CrlrAnalyticsRoute: CrlrAnalyticsRoute,
  CrlrAttendanceRoute: CrlrAttendanceRoute,
  CrlrDashboardRoute: CrlrDashboardRoute,
  CrlrNotificationsRoute: CrlrNotificationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
