/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminAlertsRouteImport } from './routes/admin.alerts'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminCrLrRouteImport } from './routes/admin.cr-lr'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminMentorsRouteImport } from './routes/admin.mentors'
import { Route as AdminSessionsRouteImport } from './routes/admin.sessions'
import { Route as AdminStudentAnalyticsRouteImport } from './routes/admin.student-analytics'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminTimetableRouteImport } from './routes/admin.timetable'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as CrlrAnalyticsRouteImport } from './routes/crlr.analytics'
import { Route as CrlrAttendanceRouteImport } from './routes/crlr.attendance'
import { Route as CrlrDashboardRouteImport } from './routes/crlr.dashboard'
import { Route as CrlrNotificationsRouteImport } from './routes/crlr.notifications'
import { Route as CrlrStudentAttendanceRouteImport } from './routes/crlr.student-attendance'
import { Route as CrlrTimetableRouteImport } from './routes/crlr.timetable'
import { Route as MentorAbsenteesRouteImport } from './routes/mentor.absentees'
import { Route as MentorAnalyticsRouteImport } from './routes/mentor.analytics'
import { Route as MentorLoginRouteImport } from './routes/mentor.login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAlertsRoute = AdminAlertsRouteImport.update({
  id: '/admin/alerts',
  path: '/admin/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCrLrRoute = AdminCrLrRouteImport.update({
  id: '/admin/cr-lr',
  path: '/admin/cr-lr',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMentorsRoute = AdminMentorsRouteImport.update({
  id: '/admin/mentors',
  path: '/admin/mentors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSessionsRoute = AdminSessionsRouteImport.update({
  id: '/admin/sessions',
  path: '/admin/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentAnalyticsRoute = AdminStudentAnalyticsRouteImport.update({
  id: '/admin/student-analytics',
  path: '/admin/student-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/admin/students',
  path: '/admin/students',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTimetableRoute = AdminTimetableRouteImport.update({
  id: '/admin/timetable',
  path: '/admin/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CrlrAnalyticsRoute = CrlrAnalyticsRouteImport.update({
  id: '/crlr/analytics',
  path: '/crlr/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CrlrAttendanceRoute = CrlrAttendanceRouteImport.update({
  id: '/crlr/attendance',
  path: '/crlr/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const CrlrDashboardRoute = CrlrDashboardRouteImport.update({
  id: '/crlr/dashboard',
  path: '/crlr/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CrlrNotificationsRoute = CrlrNotificationsRouteImport.update({
  id: '/crlr/notifications',
  path: '/crlr/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const CrlrStudentAttendanceRoute = CrlrStudentAttendanceRouteImport.update({
  id: '/crlr/student-attendance',
  path: '/crlr/student-attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const CrlrTimetableRoute = CrlrTimetableRouteImport.update({
  id: '/crlr/timetable',
  path: '/crlr/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorAbsenteesRoute = MentorAbsenteesRouteImport.update({
  id: '/mentor/absentees',
  path: '/mentor/absentees',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorAnalyticsRoute = MentorAnalyticsRouteImport.update({
  id: '/mentor/analytics',
  path: '/mentor/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorLoginRoute = MentorLoginRouteImport.update({
  id: '/mentor/login',
  path: '/mentor/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/cr-lr': typeof AdminCrLrRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mentors': typeof AdminMentorsRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/student-analytics': typeof AdminStudentAnalyticsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/timetable': typeof AdminTimetableRoute
  '/auth/login': typeof AuthLoginRoute
  '/crlr/analytics': typeof CrlrAnalyticsRoute
  '/crlr/attendance': typeof CrlrAttendanceRoute
  '/crlr/dashboard': typeof CrlrDashboardRoute
  '/crlr/notifications': typeof CrlrNotificationsRoute
  '/crlr/student-attendance': typeof CrlrStudentAttendanceRoute
  '/crlr/timetable': typeof CrlrTimetableRoute
  '/mentor/absentees': typeof MentorAbsenteesRoute
  '/mentor/analytics': typeof MentorAnalyticsRoute
  '/mentor/login': typeof MentorLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/cr-lr': typeof AdminCrLrRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mentors': typeof AdminMentorsRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/student-analytics': typeof AdminStudentAnalyticsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/timetable': typeof AdminTimetableRoute
  '/auth/login': typeof AuthLoginRoute
  '/crlr/analytics': typeof CrlrAnalyticsRoute
  '/crlr/attendance': typeof CrlrAttendanceRoute
  '/crlr/dashboard': typeof CrlrDashboardRoute
  '/crlr/notifications': typeof CrlrNotificationsRoute
  '/crlr/student-attendance': typeof CrlrStudentAttendanceRoute
  '/crlr/timetable': typeof CrlrTimetableRoute
  '/mentor/absentees': typeof MentorAbsenteesRoute
  '/mentor/analytics': typeof MentorAnalyticsRoute
  '/mentor/login': typeof MentorLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/cr-lr': typeof AdminCrLrRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mentors': typeof AdminMentorsRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/student-analytics': typeof AdminStudentAnalyticsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/timetable': typeof AdminTimetableRoute
  '/auth/login': typeof AuthLoginRoute
  '/crlr/analytics': typeof CrlrAnalyticsRoute
  '/crlr/attendance': typeof CrlrAttendanceRoute
  '/crlr/dashboard': typeof CrlrDashboardRoute
  '/crlr/notifications': typeof CrlrNotificationsRoute
  '/crlr/student-attendance': typeof CrlrStudentAttendanceRoute
  '/crlr/timetable': typeof CrlrTimetableRoute
  '/mentor/absentees': typeof MentorAbsenteesRoute
  '/mentor/analytics': typeof MentorAnalyticsRoute
  '/mentor/login': typeof MentorLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/alerts'
    | '/admin/analytics'
    | '/admin/cr-lr'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/mentors'
    | '/admin/sessions'
    | '/admin/student-analytics'
    | '/admin/students'
    | '/admin/timetable'
    | '/auth/login'
    | '/crlr/analytics'
    | '/crlr/attendance'
    | '/crlr/dashboard'
    | '/crlr/notifications'
    | '/crlr/student-attendance'
    | '/crlr/timetable'
    | '/mentor/absentees'
    | '/mentor/analytics'
    | '/mentor/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/alerts'
    | '/admin/analytics'
    | '/admin/cr-lr'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/mentors'
    | '/admin/sessions'
    | '/admin/student-analytics'
    | '/admin/students'
    | '/admin/timetable'
    | '/auth/login'
    | '/crlr/analytics'
    | '/crlr/attendance'
    | '/crlr/dashboard'
    | '/crlr/notifications'
    | '/crlr/student-attendance'
    | '/crlr/timetable'
    | '/mentor/absentees'
    | '/mentor/analytics'
    | '/mentor/login'
  id:
    | '__root__'
    | '/'
    | '/admin/alerts'
    | '/admin/analytics'
    | '/admin/cr-lr'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/mentors'
    | '/admin/sessions'
    | '/admin/student-analytics'
    | '/admin/students'
    | '/admin/timetable'
    | '/auth/login'
    | '/crlr/analytics'
    | '/crlr/attendance'
    | '/crlr/dashboard'
    | '/crlr/notifications'
    | '/crlr/student-attendance'
    | '/crlr/timetable'
    | '/mentor/absentees'
    | '/mentor/analytics'
    | '/mentor/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAlertsRoute: typeof AdminAlertsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCrLrRoute: typeof AdminCrLrRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMentorsRoute: typeof AdminMentorsRoute
  AdminSessionsRoute: typeof AdminSessionsRoute
  AdminStudentAnalyticsRoute: typeof AdminStudentAnalyticsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminTimetableRoute: typeof AdminTimetableRoute
  AuthLoginRoute: typeof AuthLoginRoute
  CrlrAnalyticsRoute: typeof CrlrAnalyticsRoute
  CrlrAttendanceRoute: typeof CrlrAttendanceRoute
  CrlrDashboardRoute: typeof CrlrDashboardRoute
  CrlrNotificationsRoute: typeof CrlrNotificationsRoute
  CrlrStudentAttendanceRoute: typeof CrlrStudentAttendanceRoute
  CrlrTimetableRoute: typeof CrlrTimetableRoute
  MentorAbsenteesRoute: typeof MentorAbsenteesRoute
  MentorAnalyticsRoute: typeof MentorAnalyticsRoute
  MentorLoginRoute: typeof MentorLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/alerts': {
      id: '/admin/alerts'
      path: '/admin/alerts'
      fullPath: '/admin/alerts'
      preLoaderRoute: typeof AdminAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cr-lr': {
      id: '/admin/cr-lr'
      path: '/admin/cr-lr'
      fullPath: '/admin/cr-lr'
      preLoaderRoute: typeof AdminCrLrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/mentors': {
      id: '/admin/mentors'
      path: '/admin/mentors'
      fullPath: '/admin/mentors'
      preLoaderRoute: typeof AdminMentorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sessions': {
      id: '/admin/sessions'
      path: '/admin/sessions'
      fullPath: '/admin/sessions'
      preLoaderRoute: typeof AdminSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/student-analytics': {
      id: '/admin/student-analytics'
      path: '/admin/student-analytics'
      fullPath: '/admin/student-analytics'
      preLoaderRoute: typeof AdminStudentAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/admin/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/timetable': {
      id: '/admin/timetable'
      path: '/admin/timetable'
      fullPath: '/admin/timetable'
      preLoaderRoute: typeof AdminTimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crlr/analytics': {
      id: '/crlr/analytics'
      path: '/crlr/analytics'
      fullPath: '/crlr/analytics'
      preLoaderRoute: typeof CrlrAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crlr/attendance': {
      id: '/crlr/attendance'
      path: '/crlr/attendance'
      fullPath: '/crlr/attendance'
      preLoaderRoute: typeof CrlrAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crlr/dashboard': {
      id: '/crlr/dashboard'
      path: '/crlr/dashboard'
      fullPath: '/crlr/dashboard'
      preLoaderRoute: typeof CrlrDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crlr/notifications': {
      id: '/crlr/notifications'
      path: '/crlr/notifications'
      fullPath: '/crlr/notifications'
      preLoaderRoute: typeof CrlrNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crlr/student-attendance': {
      id: '/crlr/student-attendance'
      path: '/crlr/student-attendance'
      fullPath: '/crlr/student-attendance'
      preLoaderRoute: typeof CrlrStudentAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crlr/timetable': {
      id: '/crlr/timetable'
      path: '/crlr/timetable'
      fullPath: '/crlr/timetable'
      preLoaderRoute: typeof CrlrTimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/absentees': {
      id: '/mentor/absentees'
      path: '/mentor/absentees'
      fullPath: '/mentor/absentees'
      preLoaderRoute: typeof MentorAbsenteesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/analytics': {
      id: '/mentor/analytics'
      path: '/mentor/analytics'
      fullPath: '/mentor/analytics'
      preLoaderRoute: typeof MentorAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/login': {
      id: '/mentor/login'
      path: '/mentor/login'
      fullPath: '/mentor/login'
      preLoaderRoute: typeof MentorLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAlertsRoute: AdminAlertsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCrLrRoute: AdminCrLrRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMentorsRoute: AdminMentorsRoute,
  AdminSessionsRoute: AdminSessionsRoute,
  AdminStudentAnalyticsRoute: AdminStudentAnalyticsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminTimetableRoute: AdminTimetableRoute,
  AuthLoginRoute: AuthLoginRoute,
  CrlrAnalyticsRoute: CrlrAnalyticsRoute,
  CrlrAttendanceRoute: CrlrAttendanceRoute,
  CrlrDashboardRoute: CrlrDashboardRoute,
  CrlrNotificationsRoute: CrlrNotificationsRoute,
  CrlrStudentAttendanceRoute: CrlrStudentAttendanceRoute,
  CrlrTimetableRoute: CrlrTimetableRoute,
  MentorAbsenteesRoute: MentorAbsenteesRoute,
  MentorAnalyticsRoute: MentorAnalyticsRoute,
  MentorLoginRoute: MentorLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
